<?php
/**
 * Implementation of hook_help().
 */
function acro_custom_site_settings_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#acro_custom_site__settings":
      $output .= '<p>'. t("Customized Settings to enable functionality for certain pages.") .'</p>';
    return $output;
  }
}

/**
 * Implementation of hook_admin().
 */
function acro_custom_site_settings_admin() {
  $form = array();

  $form['contact_header_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Contact Header Text'),
    '#default_value' => variable_get('contact_header_text', NULL),
    '#required' => FALSE,
  );
  $form['contact_header_phone'] = array(
    '#type' => 'textfield',
    '#title' => t('Contact Header Phone Number'),
    '#default_value' => variable_get('contact_header_phone', NULL),
    '#required' => FALSE,
  );
  $form['contact_header_email'] = array(
    '#type' => 'textfield',
    '#title' => t('Contact Header E-mail Address'),
    '#default_value' => variable_get('contact_header_email', NULL),
    '#required' => FALSE,
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_menu().
 */
function acro_custom_site_settings_menu() {
  $items = array();

  $items['admin/content/custom-site-settings'] = array(
    'title' => 'Custom Site Settings',
    'description' => 'Setup for Custom Data and Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('acro_custom_site_settings_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
